RDKCOM-2793: REFPLTB-1490: ccsp-home-security - Resolve all build warnings
Reason for change: Have to clear all warnings/errors with respect to 64bit architecture
hdk_device.c:802:53: error: '%s' directive output may be truncated writing up to 16383 bytes into a region of size 300 [-Werror=format-truncation=]
|   802 |                 snprintf(tmpPath, sizeof(tmpPath), "%sYiaddr", insPath[i]);
Test Procedure: build should be success on both 64bit and 32bit arch
Risks: Low
Signed-off-by: kpandu549 <keerthana_pandurangan@comcast.com>

(cherry picked from commit d66fba4967ebc59a3cfe8a919022ef7454c9399e)
Change-Id: I83a73cc168ebecb32fa1fde4900483d2514a58b3